
local function stage_button_events(action_id, action, button_id, stage_id, is_over)
	local stage_button = gui.get_node(button_id)

	if gui.get_scale(stage_button).x == 0 then
		gui.set_scale(stage_button, vmath.vector3(1, 1, 1))
	end

	is_over = is_over or false

	if action_id == nil then
		if gui.pick_node(stage_button, action.x, action.y) then
			if not is_over then
				gui.animate(stage_button, gui.PROP_SCALE, vmath.vector3(1.2, 1.2, 1), gui.EASING_OUT, 0.2)
				is_over = true
			end
		else
			if is_over then
				gui.animate(stage_button, gui.PROP_SCALE, vmath.vector3(1, 1, 1), gui.EASING_IN, 0.2)
				is_over = false
			end
		end
	end

	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(stage_button, action.x, action.y) then
			gui.animate(stage_button, gui.PROP_SCALE, vmath.vector3(0.9, 0.9, 1), gui.EASING_INOUT, 0.1, 0, function()
				gui.animate(stage_button, gui.PROP_SCALE, vmath.vector3(1, 1, 1), gui.EASING_OUT, 0.1)
			end)

			msg.post("proxy:/controller#controller", stage_id)
		end
	end

	return is_over
end


function init(self)
	msg.post(".", "acquire_input_focus")
end

local start_button_is_over = false

function on_input(self, action_id, action)
	start_button_is_over = stage_button_events(action_id, action, "start", "show_level1", start_button_is_over)
end


